name = "No Friendly Fire from Willow"
description = [[
== ENGLISH ==
Completely rebalances Willow's fire penalties so allies don't suffer negative effects when fighting alongside her.

Features included:
- Allies DO NOT suffer overheating from any Willow flame or skill (lunar, shadow, combustion, ignite, etc).
- Allies DO NOT suffer proximity penalties like freezing damage or burn-ticks from Willow's skills.
- Allies DO NOT take damage when attacking enemies burning from Willow's fire/skills.
- Dropped items DO NOT smolder when exposed to heat from Willow's abilities.
- Fire from Willow's skills DOES NOT spread to the environment (trees, flowers, beehives, structures, etc).
- Willow's attacks and skills properly tag fire sources, ensuring compatibility across all mod modules.

Everything is individually configurable, but all features are enabled by default.

== PORTUGUÊS ==
Rebalanceia totalmente as penalidades de fogo da Willow para que aliados não sofram efeitos negativos ao combater ao lado dela.

Funcionalidades incluídas:
- Aliados NÃO sofrem overheating causado por nenhuma chama ou skill da Willow (lunar, shadow, combustion, ignite, etc).
- Aliados NÃO sofrem penalidades de proximidade como freezing damage ou burn-ticks gerados pelas skills da Willow.
- Aliados NÃO recebem dano ao atacar inimigos queimando por fogo/skills da Willow.
- Itens dropados NÃO entram em smoldering ao serem expostos ao calor gerado pelas habilidades da Willow.
- O fogo originado das skills da Willow NÃO se espalha para o ambiente (árvores, flores, colmeias, estruturas, etc).
- Ataques e skills da Willow passam a marcar corretamente as fontes de fogo, garantindo compatibilidade com todos os módulos do mod.

Tudo é configurável individualmente, mas vem totalmente ativado por padrão.
]]
author = "Nuntchi"
version = "1.1.0"
dst_compatible = true
all_clients_require_mod = true
client_only_mod = false
server_filter_tags = {"willow", "fire", "allies", "friendly fire"}

configuration_options =
{
    {
        name = "NO_WILLOW_OVERHEAT",
        label = "No Willow Overheating",
        hover = "Allies won't suffer temperature increase from Willow's fire skill heat sources.",
        options = {
            {description = "Enabled (default)", data = true},
            {description = "Disabled", data = false},
        },
        default = true,
    },

    {
        name = "NO_WILLOW_AOE_PENALTIES",
        label = "No Proximity Penalties",
        hover = "Cancels freezing damage, burn ticks, and other area penalties from Willow's abilities.",
        options = {
            {description = "Enabled (default)", data = true},
            {description = "Disabled", data = false},
        },
        default = true,
    },

    {
        name = "NO_BURN_DAMAGE_ON_HITTING",
        label = "No Damage When Hitting Burning Targets",
        hover = "Players don't take damage when hitting mobs ignited by Willow's fire/skills.",
        options = {
            {description = "Enabled (default)", data = true},
            {description = "Disabled", data = false},
        },
        default = true,
    },

    {
        name = "NO_SMOLDERING_FROM_WILLOW",
        label = "No Willow-Caused Smoldering",
        hover = "Objects and dropped items don't start smoldering from heat generated by Willow's abilities.",
        options = {
            {description = "Enabled (default)", data = true},
            {description = "Disabled", data = false},
        },
        default = true,
    },

    {
        name = "NO_WILLOW_FIRE_SPREAD",
        label = "No Willow Fire Spread",
        hover = "Fire from Willow's skills DOES NOT spread to trees, plants, and structures. Behaves like torch fire.",
        options = {
            {description = "Enabled (default)", data = true},
            {description = "Disabled", data = false},
        },
        default = true,
    },

    {
        name = "ENABLE_WILLOW_TAGGING",
        label = "Automatic Skill Tagging",
        hover = "Properly identifies all flames, explosions, and effects created by Willow to ensure full compatibility between modules.",
        options = {
            {description = "Enabled (default)", data = true},
            {description = "Disabled (not recommended)", data = false},
        },
        default = true,
    },

    {
        name = "SHOW_VISUAL_INDICATOR",
        label = "Visual Protection Indicator",
        hover = "Shows a small icon near your character when Willow's fire protection is active.",
        options = {
            {description = "Enabled", data = true},
            {description = "Disabled (default)", data = false},
        },
        default = false,
    },
}